[features]
seeds = false
skip-lint = false
[programs.localnet]
calculator = "26L2GoSag9GGJDgqcB1jJwYsEJCPPRnDUdRhUkn8Xktf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "validator-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
